export default {
  darkMode: 'class',
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        heritage: {
          primary: 'var(--color-primary)',
          'primary-hover': 'var(--color-primary-hover)',
          'primary-light': 'var(--color-primary-light)',
          'primary-dark': 'var(--color-primary-dark)',
          secondary: 'var(--color-secondary)',
          'secondary-hover': 'var(--color-secondary-hover)',
          accent: 'var(--color-accent)',
          'accent-hover': 'var(--color-accent-hover)',
          background: 'var(--color-background)',
          'background-secondary': 'var(--color-background-secondary)',
          'background-tertiary': 'var(--color-background-tertiary)',
          surface: 'var(--color-surface)',
          'surface-hover': 'var(--color-surface-hover)',
          text: {
            primary: 'var(--color-text-primary)',
            secondary: 'var(--color-text-secondary)',
            muted: 'var(--color-text-muted)',
            inverse: 'var(--color-text-inverse)',
          },
          border: 'var(--color-border)',
          'border-light': 'var(--color-border-light)',
          'border-focus': 'var(--color-border-focus)',
          success: 'var(--color-success)',
          warning: 'var(--color-warning)',
          error: 'var(--color-error)',
          info: 'var(--color-info)',
        },
        wood: {
          deep: "#5d4037",
          medium: "#8d6e63",
          light: "#d7ccc8",
          cream: "#faf9f6",
        },
        primary: {
          deep: "#8b4513",
          medium: "#a0522d",
          light: "#d2b48c",
          cream: "#faf9f6",
        },
        blue: {
          deep: "#1e3a8a",
          primary: "#3b82f6",
          light: "#93c5fd",
          sky: "#dbeafe",
        },
        gold: {
          primary: "#daa520",
          light: "#f4e5b2",
          dark: "#aa8c2c",
        },
        entity: {
          inheritor: "#8B5CF6",
          technique: "#10B981",
          work: "#F59E0B",
          pattern: "#EF4444",
          region: "#06B6D4",
          period: "#6366F1",
          material: "#84CC16",
        },
      },
      fontFamily: {
        heading: ['var(--font-heading)', '"Noto Serif SC"', '"Source Han Serif SC"', '"Songti SC"', "serif"],
        body: ['var(--font-body)', '"Noto Sans SC"', '"PingFang SC"', '"Microsoft YaHei"', "sans-serif"],
        mono: ['var(--font-mono)', '"Fira Code"', '"SF Mono"', "Monaco", '"Courier New"', "monospace"],
      },
      fontSize: {
        xs: "12px",
        sm: "14px",
        base: "16px",
        lg: "18px",
        xl: "22px",
        "2xl": "28px",
        "3xl": "36px",
        "4xl": "48px",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
      },
      boxShadow: {
        sm: "0 2px 8px var(--color-shadow)",
        md: "0 4px 16px var(--color-shadow)",
        lg: "0 8px 24px var(--color-shadow)",
        xl: "0 12px 32px var(--color-shadow)",
        "2xl": "0 16px 48px var(--color-shadow)",
        inner: "inset 0 2px 4px var(--color-shadow)",
        glow: "0 0 20px var(--color-shadow-glow)",
        "glow-lg": "0 0 40px var(--color-shadow-glow)",
        heritage: "var(--color-shadow)",
        "heritage-glow": "var(--color-shadow-glow)",
      },
      borderRadius: {
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "20px",
        "3xl": "24px",
      },
      backgroundImage: {
        'heritage-primary': 'var(--gradient-primary)',
        'heritage-secondary': 'var(--gradient-secondary)',
        'heritage-accent': 'var(--gradient-accent)',
        'heritage-bg': 'var(--gradient-background)',
        'heritage-card': 'var(--gradient-card)',
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-in": "slideIn 0.3s ease-out",
        "slide-up": "slideUp 0.3s ease-out",
        "scale-in": "scaleIn 0.2s ease-out",
        "bounce-in": "bounceIn 0.3s ease-out",
        "node-enter": "nodeEnter 0.5s ease-out",
        "draw-line": "drawLine 1s ease-out forwards",
        "shimmer": "shimmer 2s linear infinite",
        "float": "float 3s ease-in-out infinite",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideIn: {
          "0%": { opacity: "0", transform: "translateX(-20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        bounceIn: {
          "0%": { opacity: "0", transform: "scale(0.3)" },
          "50%": { transform: "scale(1.05)" },
          "70%": { transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        nodeEnter: {
          "0%": { opacity: "0", transform: "scale(0)" },
          "70%": { transform: "scale(1.1)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        drawLine: {
          "0%": { strokeDashoffset: "1000" },
          "100%": { strokeDashoffset: "0" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 20px var(--color-shadow-glow)" },
          "50%": { boxShadow: "0 0 40px var(--color-shadow-glow)" },
        },
      },
      transitionDuration: {
        fast: "150ms",
        normal: "300ms",
        slow: "500ms",
      },
      transitionTimingFunction: {
        "ease-in": "cubic-bezier(0.4, 0, 1, 1)",
        "ease-out": "cubic-bezier(0, 0, 0.2, 1)",
        "ease-in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
        "ease-bounce": "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [],
};
